

title: PEA 2
email: julio@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  TRABAJO DE PEA 2 PALACIOS MENDOZA.
baseurl: "/PEA2_PalaciosMendoza" # the subpath of your site, e.g. /blog
url: "https://juli027.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mandarinas
github_username:  juli027

# Build settings
theme: minima
plugins:
  - jekyll-feed

